### ISSUE TITLE
About keysize confusion attack 

### ISSUE THREAD

**Issue by RayCxggg** [luojiazhishu/BLE-SC-Pairing-Model#1]
Hi, 

I am a huge fun of your work. It seems that the keysize confusion attack is a critical specification flaw which potentially affects all BLE devices. I wonder whether the Bluetooth SIG has ever reached out to you since there is no official advisory that indicates the SIG has noticed this attack. If they did, how do they plan to patch the vulnerability? Does the latest Core Specification v5.4 fix it?

Thanks.

**Comment by itachi321** [comment]
Hello,

We have reported the keysize confusion attack and our countermeasure to Bluetooth SIG. The Bluetooth SIG has acknowledged our findings. They also claim that manufacturers are free to adopt our fixes during implementation, but it is atypical to be recommended or mandatory in the core specification since our fixes require additional steps from a user.
We will publish some details of the interactions with Bluetooth SIG in this depository.

Thanks.

**Comment by RayCxggg** [comment]
Thanks. Would love to follow on the update since it seems to be a serious vulnerability of BLE specification.
